# - hosts: max-dhcp
#   tasks:
#     - name: debug hostvars
#       debug: var=hostvars['max-gateway'].ansible_default_ipv4.macaddress
#       register: mac_address
# pre_tasks:
#   - name: set facts gateway
#     when: "{{ 'max-gateway' in ansible_facts.hostname }}"
#     ansible.builtin.set_fact:
#       mac_address: "{{ ansible_facts]['macaddress']|default(None) }}"

# - name: debug hostvars
#   debug: var=mac_address

- hosts: max-gateway
  tasks:
    - name: gateway tasks
      include_role:
        name: gateway
# - hosts: max-gateway
#   tasks:
#     - name: Pause for 1 minutes to give it some time
#       ansible.builtin.pause:
#         minutes: 1

# - hosts: max-dhcp
#   tasks:
#     - name: Pause for 1 minutes to give it some time
#       ansible.builtin.pause:
#         minutes: 1

- hosts: max-dhcp
  vars_files:
    - vars/main.yml
  tasks:
    - name: dhcp
      include_tasks: tasks/main.yml
# - hosts: max-dhcp
#   tasks:
#     - name: dhcp tasks
#       include_role:
#         name: dhcp

# - hosts: max-dns
#   tasks:
#     - name: Pause for 2 minutes to give it some time
#       ansible.builtin.pause:
#         minutes: 2

- hosts: max-dns
  tasks:
    - name: dns tasks
      include_role:
        name: dns
# - hosts: max-gateway
#   tasks:
#     - name: network manager
#       service:
#         name: NetworkManager
#         state: restarted
# - hosts: max-node
#   tasks:
#     - name: node tasks
#       include_role:
#         name: node
