- hosts: all
  tasks:
    - name: loop groups
      user:
        name: "{{ item }}"
        state: present
        groups: "wheel"
      loop: "{{ groups['all'] }}"

# - hosts: all
#   tasks:
#     - name: loop dns hosts
#       user:
#         name: "{{ item2 }}"
#         state: present
#         groups: "wheel"
#       loop:
#         - 0
#         - 1
#         - 2
#         - 3
- hosts: all
  tasks:
    - name: Output idx
      debug:
        var: my_idx
#       loop: "{{ rn2 }}"
#       loop_control:
#         index_var: my_idx

- hosts: all
  tasks:
    - name: set url
      when: "{{ item in ansible_facts.hostname }}"
      set_fact:
        node_target: "{{ hostvars[ item ].molecule_yml.platforms[ my_idx ].group }}"
      loop: "{{ groups['all'] }}"
      loop_control:
        index_var: my_idx

# - hosts: max-dhcp
#   tasks:
#     - name: debug hostvars
#       debug: var=groups

- hosts: all
  tasks:
    - name: debug node_target
      debug: var=node_target
# pre_tasks:
#   - name: set facts gateway
#     when: "{{ 'max-gateway' in ansible_facts.hostname }}"
#     ansible.builtin.set_fact:
#       mac_address: "{{ ansible_facts]['macaddress']|default(None) }}"

# - name: debug hostvars
#   debug: var=mac_address

- hosts: max-gateway
  tasks:
    - name: gateway tasks
      include_role:
        name: gateway
# - hosts: max-gateway
#   tasks:
#     - name: Pause for 1 minutes to give it some time
#       ansible.builtin.pause:
#         minutes: 1

# - hosts: max-dhcp
#   tasks:
#     - name: Pause for 1 minutes to give it some time
#       ansible.builtin.pause:
#         minutes: 1

- hosts: max-dhcp
  vars_files:
    - vars/main.yml
  tasks:
    - name: dhcp
      include_tasks: tasks/main.yml
# - hosts: max-dhcp
#   tasks:
#     - name: dhcp tasks
#       include_role:
#         name: dhcp

- hosts: max-dns
  tasks:
    - name: Pause for 2 minutes to give it some time
      ansible.builtin.pause:
        minutes: 2

- hosts: max-dns
  tasks:
    - name: dns tasks
      include_role:
        name: dns
# - hosts: max-gateway
#   tasks:
#     - name: network manager
#       service:
#         name: NetworkManager
#         state: restarted

# - hosts: all
#   tasks:
#     - name: loop hosts
#       user:
#         name: "{{ item }}"
#         state: present
#         groups: "wheel"
#       loop:
#         - "{{ hostvars['max-gateway'].ansible_all_ipv4_addresses[1] }}"
#         - "{{ hostvars['max-dhcp'].ansible_all_ipv4_addresses[1] }}"
#         - "{{ hostvars['max-dns'].ansible_all_ipv4_addresses[1] }}"

- hosts: all
  tasks:
    - name: debug node_target
      debug: var=node_target

- hosts: all
  tasks:
    - name: node tasks
      include_role:
        name: node
