---
- src: https://github.com/EAS-Max/molecule_gateway
  scm: git
  version: main
  name: gateway
# - src: https://github.com/EAS-Max/molecule-dhcp
#   scm: git
#   version: variables
#   name: dhcp

- src: https://github.com/EAS-Max/molecule-dns
  scm: git
  version: variable
  name: dns

- src: https://github.com/EAS-Max/molecule_node
  scm: git
  version: variable
  name: node
