---
# tasks file for dhcp
- name: refresh subscription manager
  command: subscription-manager refresh

- name: Install dhcp-server
  ansible.builtin.yum:
    name: dhcp
    state: latest

# - name: set wired connection conf
#   blockinfile:
#     dest: /etc/sysconfig/network-scripts/ifcfg-ens224
#     block: |
#       TYPE=Ethernet
#       PROXY_METHOD=none
#       BROWSER_ONLY=no
#       BOOTPROTO=none
#       DEFROUTE=yes
#       IPV4_FAILURE_FATAL=no
#       IPV6INIT=yes
#       IPV6_AUTOCONF=yes
#       IPV6_DEFROUTE=yes
#       IPV6_FAILURE_FATAL=no
#       NAME=ens224
#       UUID=32d7c5eb-362e-4764-8ddd-847ab5c94e8e
#       DEVICE=ens224
#       ONBOOT=yes
#       PREFIX=8
#       IPADDR={{ dns | default('default_value')}}
#       GATEWAY=10.0.0.1
#       DNS1=8.8.8.8
#       DOMAIN="max.local"

#     insertafter: EOF

- name: set gateway in network
  blockinfile:
    dest: /etc/dhcp/dhcpd.conf
    block: |
      default-lease-time 600; 
      max-lease-time 7200; 
      ddns-update-style none;
      authoritative;
      subnet {{ subnet }} netmask 255.255.255.0 {
        range {{ sub_range }};				
        option routers 10.0.0.1;						
        option subnet-mask 255.255.255.0;
        option domain-name "{{ domain }}.local";
        option domain-search "{{ domain }}.local";
        option domain-name-servers {{ dns }}, 8.8.8.8, 8.8.4.4;
      }

    insertafter: EOF
    create: yes
# I will add our dns once it is needed
- name: firewall command
  command: firewall-cmd --add-service=dhcp --permanent

# - name: Add dhcpd service permanent
#   ansible.posix.firewalld:
#     service: dhcp
#     permanent: yes
#     state: enabled

- name: reloading firewalld
  service:
    name: firewalld
    state: restarted

- name: network manager
  service:
    name: NetworkManager
    state: restarted

- name: dhcpd service
  service:
    name: dhcpd
    state: started
